version: "3.9"

services:
  mysql:
    image: "mysql"
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./backend/docker/provision/mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - mysql_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

networks:
  mysql_network:
    driver: bridge

volumes:
  db_data:
