version: "3.9"

services:
  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./docker/provision/mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - mysql_network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-ppassword"
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge

volumes:
  db_data:
